apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqproducer
spec:
  selector:
    matchLabels:
      app: mqproducer
  template:
    metadata:
      labels:
        app: mqproducer
    spec:
      containers:
      - name: mqproducer
        image: w8873docker/mqproducer:1.0.0
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: mqproducer
spec:
  type: NodePort
  selector:
    app: mqproducer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32600
